# Generated by Django 3.2.20 on 2023-08-26 15:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='review',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True, verbose_name='Ревью'),
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to='files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['py'])], verbose_name='Файл'),
        ),
    ]
